
[env]
TERM = "xterm-256color"

[general]
import = [
"themes/themes/ayu_dark.toml"
]

[font]
size = 9 
normal = { family = "3270 Nerd Font", style = "Regular" }

# Disable below comments when copying to .../AppData/Roaming/alacritty
# Used to start alacritty in wsl
# [terminal]
# shell = { program = "wsl.exe", args = ["~"] }

[terminal]
shell = "fish"



[mouse]
hide_when_typing = true

[window]
opacity = 0.80
startup_mode = "Maximized"
padding = {x = 5, y = 5}

[cursor]
style = { shape = "Underline", blinking = "On"}

